### ISSUE TITLE
git "fatal: ambiguous argument" on re-deploy of app

### ISSUE THREAD

**Issue by jney** [heroku/heroku-kong#11]
I've got the following error when i try to deploy to heroku right now.

```
remote: -----> Building Kong from https://github.com/mars/kong.git#0.7.0-external-supervisor.1
remote:
remote: Error: Could not find rock 'kong' in /app/.heroku
remote: fatal: ambiguous argument 'origin/0.7.0-external-supervisor.1': unknown revision or path not in the working tree.
remote: Use '--' to separate paths from revisions, like this:
remote: 'git <command> [<revision>...] -- [<file>...]'
```

**Comment by mars** [comment]
Attempting to reproduce this error, I just ran a fresh deploy from the purple "Deploy on Heroku" button. My deploy succeeded; here's the log from the section where you encountered the error:

```
-----> Building Kong from https://github.com/mars/kong.git#0.7.0-external-supervisor.1
Error: Could not find rock 'kong' in /app/.heroku
Cloning into '/app/tmp/cache/heroku-kong-buildpack/kong-source'...
Note: checking out '0.7.0-external-supervisor.1'.
```

Can you provide further details about the situation where you encountered the error? What does "upgrading" mean in this context?

**Comment by jney** [comment]
> What does "upgrading" mean in this context?

the word indeed was not appropriate, i meant a deployment on an existing heroku app

I just tried from a fresh install and it worked, but re-deploying still doesn't

**Comment by jney** [comment]
here are the full logs https://gist.github.com/jney/b3cd1f8015186f6c3e58584df86fa2a8

**Comment by mars** [comment]
I've reproduced your error; will follow-up once I have more information.

**Comment by mars** [comment]
I'm not sure why this began failing recently, but I [applied a fix](https://github.com/heroku/heroku-buildpack-kong/compare/v3.1.0...v3.1.2) to make git fetch the correct Kong source code.

You can update your heroku-kong app to the [Beta 5 release](https://github.com/heroku/heroku-kong/releases/tag/v1.0.0-beta.5) or to master to get the fix.

Thanks for filing this issue @jney.
