### ISSUE TITLE
Present on the Kong community call

### ISSUE THREAD

**Issue by judithpatudith** [heroku/heroku-kong#24]
Hi Mars! Are you interested in demo-ing this project on the [Kong community call](https://docs.google.com/document/d/1heIynPTVcHn13BXMJO0KiOr8bTmbhzVxJe5yajp4Xz4/edit?usp=sharing) or sharing it in our [Ingegrations Hub](https://docs.konghq.com/hub/)? It looks really cool and we'd love to get you more exposure 🙂

**Comment by mars** [comment]
Hi @judithpatudith 😃

Sure, I'd be honored to present this project to the community. Shall I just add myself to the list & this to the topics?

Already worked with @coopr to list on the Hub: https://docs.konghq.com/hub/heroku/kong-app/

**Comment by mars** [comment]
Just added myself to the sign-up doc!

**Comment by judithpatudith** [comment]
Woot, thank you!

**Comment by judithpatudith** [comment]
👋 Thanks so much for agreeing to present on the community call tomorrow! I've added you to the calendar invite and will be on the Zoom call on the 13th (day-of) a few minutes early in case you want to test out any screen sharing.

You'll probably have about 15-20 minutes for demo + Q&A, and if you have time to make them, it would be awesome to see a couple of slides to frame the context for why you built your integration. I'd love to check those out the day before if possible and add them to the slides for posterity :) 

Let me know if you have any questions for me. I'm really excited to hear about what you built!
