### ISSUE TITLE
Is someone working on upgrading Kong to the latest version?

### ISSUE THREAD

**Issue by holgersindbaek** [heroku/heroku-kong#9]
Se we can use the free Postgres DB on Heroku instead of the $72/m Cassandra DB?

**Comment by sinzone** [comment]
@mars we just released Kong 0.9 (with SSL connection to Postgres). 

https://github.com/Mashape/kong/releases/tag/0.9.0

**Comment by mars** [comment]
I just looked at porting our [Kong patches](https://github.com/Mashape/kong/compare/master...mars:0.7.0-external-supervisor) up to 0.9.0, and the CLI codebase has totally changed. So, I'm not sure when we'll be able to perform this upgrade.

**Comment by mars** [comment]
Kong on Heroku is back using version 0.11 + Postgres.
